# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-09-12 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='productinbasket',
            options={'verbose_name': 'Item in cart', 'verbose_name_plural': 'Items in cart'},
        ),
        migrations.AlterModelOptions(
            name='productinorder',
            options={'verbose_name': 'Item in order', 'verbose_name_plural': 'Items in order'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Order status', 'verbose_name_plural': 'Orders status'},
        ),
    ]
