# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-09-12 16:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20170212_1900'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Product category', 'verbose_name_plural': 'Products category'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Photograph', 'verbose_name_plural': 'Photographs'},
        ),
    ]
